const projects=[
{id:"orient",title:"Orient Detectors",eyebrow:"Technology / 2022—2025",story:"I worked with Orient Detectors for nearly three years across campaigns, product visuals, social media, catalogs and brochures. Technical products often carry too much information for one layout, so a recurring part of the job was deciding what needed to be understood first.",scope:"Campaigns · Product communication · Social · Catalogs · Brochures",files:["g1.png","g2.png","g3.png","g4.png","g5.png","g6.png","g7.png","g8.png","g9.png"],featured:true},
{id:"realestate",title:"Real Estate Social Campaign",eyebrow:"Real Estate / Social",story:"A campaign that moves from introducing the property to details and then the offer. The message changes from post to post, while the visual language keeps the series connected.",scope:"Visual direction · Social layouts · Campaign adaptations",files:["إطلالة الفلل.png","تفاصيل الفلل.png","عرض الفلل.png"],featured:true},
{id:"ecommerce",title:"E-commerce Performance Content",eyebrow:"E-commerce / Arabic Content",story:"A content series around store performance and sales. The system stays familiar while headlines, numbers and supporting details change from one post to the next.",scope:"Social series · Arabic typography · Information hierarchy",files:["زيادة الأرباح.png","نسبة السلات.png","أرباح السلات.png"],featured:true},
{id:"healthcare",title:"Healthcare Pricing Series",eyebrow:"Healthcare / Social",story:"A repeatable pricing format for different services, designed to stay easy to scan on a phone while the service names, prices and supporting content change.",scope:"Social design · Arabic layout · Pricing hierarchy",files:["أسعار Full Body.png","أسعار ليزر المناطق.png","أسعار الهيدرافيشيال.png"],featured:true},
{id:"event",title:"Event Campaign",eyebrow:"Event / Social",story:"Two connected pieces from the same event communication set: one introduces the event, while the second carries the practical details.",scope:"Campaign layout · Event communication · Arabic typography",files:["تصوير المناسبات - رأسي.png","تفاصيل اللقاء.png"],featured:true},
{id:"natural",title:"Natural Product Visual Studies",eyebrow:"Product / Image-making",story:"A set of product-led visual studies built around ingredients, texture and atmosphere, with a consistent focus on product staging and composition.",scope:"Image direction · Product staging · Compositing",files:["01_brand_nature_rituals.png","07_natural_origins.png","٠٢.jpg","٠٣.png","٠٤.png"],featured:true},
{id:"huggies",title:"Huggies — Product Campaign Study",eyebrow:"Product / Portfolio Study",story:"A three-piece product campaign study built around one Huggies product.",scope:"Art direction · Composition · Product presentation",files:["h1.JPG","h2.JPG","h3.JPG"]},
{id:"aiarchive",title:"AI-assisted Commercial Archive",eyebrow:"Image-making / Archive",story:"A wider archive of AI-assisted commercial image work.",scope:"AI image generation · Photoshop · Compositing · Retouching",files:["ai1.jpg","ai2.jpg","ai3.jpg","ai4.jpg","ai5.jpg","ai6.jpg","ai7.jpg","ai8.jpg","ai9.jpg"]},
{id:"social",title:"Social Media Archive",eyebrow:"Social / Archive",story:"A broader set of social design work from the original portfolio archive.",scope:"Social design · Campaign adaptations · Daily content",files:["s1.png","s2.png","s3.png","s4.png","s5.png","s6.png","s7.png","s8.png","s9.png","s10.png","s11.png","s12.png","s13.png","s14.png","s15.png","s16.png","s17.png","s18.png","s19.png","s20.png","s21.png","s22.jpg","s23.jpg","s24.jpg"]},
{id:"editorial",title:"Editorial & Media Archive",eyebrow:"Editorial / Archive",story:"Poster and editorial work from the earlier part of my portfolio.",scope:"Editorial layout · Poster design · Media graphics",files:["p1.png","p2.png","p3.png","p4.png","p5.png","p6.png"]},
{id:"campaignbanners",title:"Campaign & Banner Archive",eyebrow:"Campaign / Archive",story:"Campaign and banner layouts from the original portfolio archive.",scope:"Campaign layout · Digital banners · Print adaptations",files:["b1.png","b2.png","b3.png","b4.png"]},
{id:"brandapps",title:"Brand Applications Archive",eyebrow:"Brand / Print Archive",story:"Brand applications and print-oriented pieces from the older portfolio.",scope:"Brand applications · Layout · Print",files:["c1.png","c2.png","c3.png","c4.png","c6.png","c7.png","c8.png"]},
{id:"socialartboards",title:"Social Campaign Artboards",eyebrow:"Social / Archive Set",story:"A separate run of social campaign artboards from the uploaded archive.",scope:"Social layouts · Promotional content · Arabic design",files:["العرض.png","Artboard 2.png","Artboard 3.png","Artboard 4.png","Artboard 5.png","Artboard 6.png","01.png"]},
{id:"digitalartboards",title:"Digital Campaign Artboards",eyebrow:"Digital / Archive Set",story:"Two large-format digital campaign pieces from the same exported set.",scope:"Digital campaign · Banner layout",files:["Artboard 1.png","Artboard 2 2.png"]},
{id:"covers",title:"Project Covers & Experiments",eyebrow:"Archive / Covers",story:"Standalone covers and visual experiments uploaded with the portfolio.",scope:"Cover design · Visual experiments · Project thumbnails",files:["khairzad.png","seredo.png","social-lab.png","tab-beauty.png"]}
];
const featuredProjects=projects.filter(p=>p.featured);
let currentProject=0,currentImage=0,archiveBuilt=false,webReady=false;
const $=s=>document.querySelector(s);
const projectIndex=$("#projectIndex"),projectKicker=$("#projectKicker"),projectTitle=$("#projectTitle"),projectStory=$("#projectStory"),projectScope=$("#projectScope"),projectCount=$("#projectCount"),projectHero=$("#projectHero"),heroFrame=$("#heroFrame"),filmstrip=$("#filmstrip"),fileName=$("#fileName"),imageCounter=$("#imageCounter");
const fullSrc=f=>`web/full/${f}.webp`,thumbSrc=f=>`web/thumb/${f}.webp`,displayFull=f=>webReady?fullSrc(f):f,displayThumb=f=>webReady?thumbSrc(f):f;
function renderIndex(){projectIndex.innerHTML=featuredProjects.map((p,i)=>`<button class="project-button ${i===currentProject?'active':''}" data-project="${i}" type="button"><span class="project-no">${String(i+1).padStart(2,"0")}</span><span class="project-name">${p.title}</span></button>`).join("");projectIndex.querySelectorAll(".project-button").forEach(btn=>btn.addEventListener("click",()=>{currentProject=+btn.dataset.project;currentImage=0;renderProject()}))}
function renderProject(){const p=featuredProjects[currentProject];projectKicker.textContent=p.eyebrow;projectTitle.textContent=p.title;projectStory.textContent=p.story;projectScope.textContent=p.scope;projectCount.textContent=`${p.files.length} selected pieces`;currentImage=Math.min(currentImage,p.files.length-1);filmstrip.innerHTML=p.files.map((f,i)=>webReady?`<button class="thumb ${i===currentImage?'active':''}" data-image="${i}" type="button" aria-label="Open work ${i+1}"><img src="${displayThumb(f)}" alt="" loading="lazy" decoding="async"></button>`:`<button class="thumb text-thumb ${i===currentImage?'active':''}" data-image="${i}" type="button" aria-label="Open work ${i+1}"><span>${String(i+1).padStart(2,"0")}</span></button>`).join("");filmstrip.querySelectorAll(".thumb").forEach(btn=>btn.addEventListener("click",()=>setImage(+btn.dataset.image,true)));setImage(currentImage,false);renderIndex()}
function setImage(i,scroll=true){const p=featuredProjects[currentProject];currentImage=i;projectHero.src=displayFull(p.files[i]);projectHero.alt=`${p.title} — selected work ${i+1}`;projectHero.decoding="async";fileName.textContent="";imageCounter.textContent=`${i+1} / ${p.files.length}`;filmstrip.querySelectorAll(".thumb").forEach((t,n)=>t.classList.toggle("active",n===i));if(scroll)filmstrip.querySelector(`[data-image="${i}"]`)?.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"})}
$("#prevProject").addEventListener("click",()=>{currentProject=(currentProject-1+featuredProjects.length)%featuredProjects.length;currentImage=0;renderProject()});
$("#nextProject").addEventListener("click",()=>{currentProject=(currentProject+1)%featuredProjects.length;currentImage=0;renderProject()});
const archiveOverlay=$("#archiveOverlay"),archiveBody=$("#archiveBody");
function buildArchive(){if(archiveBuilt)return;archiveBuilt=true;archiveBody.innerHTML=projects.map((p,pi)=>`<section class="archive-group"><div class="archive-group-head"><h3>${String(pi+1).padStart(2,"0")} · ${p.title}</h3><span>${p.files.length} pieces</span></div><div class="archive-grid">${p.files.map(f=>`<figure class="archive-item" data-file="${f}" data-title="${p.title}"><img src="${displayThumb(f)}" alt="${p.title}" loading="lazy" decoding="async"><figcaption>${f}</figcaption></figure>`).join("")}</div></section>`).join("");archiveBody.querySelectorAll(".archive-item").forEach(el=>el.addEventListener("click",()=>openLightbox(el.dataset.file,el.dataset.title)))}
function openArchive(){buildArchive();archiveOverlay.classList.add("open");archiveOverlay.setAttribute("aria-hidden","false");document.body.style.overflow="hidden"}
function closeArchive(){archiveOverlay.classList.remove("open");archiveOverlay.setAttribute("aria-hidden","true");document.body.style.overflow=""}
$("#archiveOpen").addEventListener("click",openArchive);$("#archiveClose").addEventListener("click",closeArchive);
const lightbox=$("#lightbox"),lightboxImage=$("#lightboxImage"),lightboxCaption=$("#lightboxCaption");
function openLightbox(src,cap){lightboxImage.src=displayFull(src);lightboxCaption.textContent=cap;lightbox.classList.add("open");lightbox.setAttribute("aria-hidden","false")}
function closeLightbox(){lightbox.classList.remove("open");lightbox.setAttribute("aria-hidden","true");lightboxImage.src=""}
heroFrame.addEventListener("click",()=>{const p=featuredProjects[currentProject];openLightbox(p.files[currentImage],p.title)});$("#lightboxClose").addEventListener("click",closeLightbox);lightbox.addEventListener("click",e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener("keydown",e=>{if(e.key==="Escape"){if(lightbox.classList.contains("open"))closeLightbox();else if(archiveOverlay.classList.contains("open"))closeArchive()}});
const root=document.documentElement,langToggle=$("#langToggle");let lang=localStorage.getItem("portfolioLang")||"en";
function applyLang(){const ar=lang==="ar";root.lang=lang;root.dir=ar?"rtl":"ltr";langToggle.textContent=ar?"EN":"AR";document.querySelectorAll("[data-en][data-ar]").forEach(el=>{const v=el.getAttribute(ar?"data-ar":"data-en");if(v.includes("<"))el.innerHTML=v;else el.textContent=v});localStorage.setItem("portfolioLang",lang)}
langToggle.addEventListener("click",()=>{lang=lang==="en"?"ar":"en";applyLang()});
async function init(){try{const r=await fetch(thumbSrc("g1.png"),{method:"HEAD",cache:"no-store"});webReady=r.ok}catch(_){webReady=false}applyLang();renderProject()}
init();