const projects=[
{id:"sociallab",title:"Social Lab",eyebrow:"SaaS Product Story / 2026",story:"A persuasive product narrative that explains an AI sales platform with direct language, clear proof and a confident visual system.",scope:"Web experience · Content hierarchy · Presentation design",files:["social-lab.png"],featured:true},
{id:"briefstudio",title:"Brief Studio",eyebrow:"Company Profile / Presentation",story:"BRIEF — Company Profile.",scope:"Company profile · Editorial layout · Presentation design",files:["brief-project-cover.svg"],featured:true},
{id:"realestate",title:"Real Estate Social Campaign",eyebrow:"Real Estate / Social",story:"A campaign that moves from introducing the property to details and then the offer. The message changes from post to post, while the visual language keeps the series connected.",scope:"Visual direction · Social layouts · Campaign adaptations",files:["إطلالة الفلل.png","تفاصيل الفلل.png","عرض الفلل.png"],featured:true},
{id:"natural",title:"Natural Product Visual Studies",eyebrow:"Product / Image-making",story:"A set of product-led visual studies built around ingredients, texture and atmosphere, with a consistent focus on product staging and composition.",scope:"Image direction · Product staging · Compositing",files:["01_brand_nature_rituals.png","07_natural_origins.png","٠٢.jpg","٠٣.png","٠٤.png"],featured:true},
{id:"ecommerce",title:"E-commerce Performance Content",eyebrow:"E-commerce / Arabic Content",story:"A content series around store performance and sales. The system stays familiar while headlines, numbers and supporting details change from one post to the next.",scope:"Social series · Arabic typography · Information hierarchy",files:["زيادة الأرباح.png","نسبة السلات.png","أرباح السلات.png"],featured:true},
{id:"orient",title:"Orient Detectors",eyebrow:"Technology / 2022—2025",story:"I worked with Orient Detectors for nearly three years across campaigns, product visuals, social media, catalogs and brochures. Technical products often carry too much information for one layout, so a recurring part of the job was deciding what needed to be understood first.",scope:"Campaigns · Product communication · Social · Catalogs · Brochures",files:["g1.png","g2.png","g3.png","g4.png","g5.png","g6.png","g7.png","g8.png","g9.png"],featured:true},
{id:"healthcare",title:"Healthcare Pricing Series",eyebrow:"Healthcare / Social",story:"A repeatable pricing format for different services, designed to stay easy to scan on a phone while the service names, prices and supporting content change.",scope:"Social design · Arabic layout · Pricing hierarchy",files:["أسعار Full Body.png","أسعار ليزر المناطق.png","أسعار الهيدرافيشيال.png"],featured:true},
{id:"event",title:"Event Campaign",eyebrow:"Event / Social",story:"Two connected pieces from the same event communication set: one introduces the event, while the second carries the practical details.",scope:"Campaign layout · Event communication · Arabic typography",files:["تصوير المناسبات - رأسي.png","تفاصيل اللقاء.png"],featured:true},
{id:"huggies",title:"Huggies — Product Campaign Study",eyebrow:"Product / Portfolio Study",story:"A three-piece product campaign study built around one Huggies product.",scope:"Art direction · Composition · Product presentation",files:["h1.JPG","h2.JPG","h3.JPG"]},
{id:"aiarchive",title:"AI-assisted Commercial Archive",eyebrow:"Image-making / Archive",story:"A wider archive of AI-assisted commercial image work.",scope:"AI image generation · Photoshop · Compositing · Retouching",files:["ai1.jpg","ai2.jpg","ai3.jpg","ai4.jpg","ai5.jpg","ai6.jpg","ai7.jpg","ai8.jpg","ai9.jpg"]},
{id:"social",title:"Social Media Archive",eyebrow:"Social / Archive",story:"A broader set of social design work from the original portfolio archive.",scope:"Social design · Campaign adaptations · Daily content",files:["s1.png","s2.png","s3.png","s4.png","s5.png","s6.png","s7.png","s8.png","s9.png","s10.png","s11.png","s12.png","s13.png","s14.png","s15.png","s16.png","s17.png","s18.png","s19.png","s20.png","s21.png","s22.jpg","s23.jpg","s24.jpg"]},
{id:"editorial",title:"Editorial & Media Archive",eyebrow:"Editorial / Archive",story:"Poster and editorial work from the earlier part of my portfolio.",scope:"Editorial layout · Poster design · Media graphics",files:["p1.png","p2.png","p3.png","p4.png","p5.png","p6.png"]},
{id:"campaignbanners",title:"Campaign & Banner Archive",eyebrow:"Campaign / Archive",story:"Campaign and banner layouts from the original portfolio archive.",scope:"Campaign layout · Digital banners · Print adaptations",files:["b1.png","b2.png","b3.png","b4.png"]},
{id:"brandapps",title:"Brand Applications Archive",eyebrow:"Brand / Print Archive",story:"Brand applications and print-oriented pieces from the older portfolio.",scope:"Brand applications · Layout · Print",files:["c1.png","c2.png","c3.png","c4.png","c6.png","c7.png","c8.png"]},
{id:"socialartboards",title:"Social Campaign Artboards",eyebrow:"Social / Archive Set",story:"A separate run of social campaign artboards from the uploaded archive.",scope:"Social layouts · Promotional content · Arabic design",files:["العرض.png","Artboard 2.png","Artboard 3.png","Artboard 4.png","Artboard 5.png","Artboard 6.png","01.png"]},
{id:"digitalartboards",title:"Digital Campaign Artboards",eyebrow:"Digital / Archive Set",story:"Two large-format digital campaign pieces from the same exported set.",scope:"Digital campaign · Banner layout",files:["Artboard 1.png","Artboard 2 2.png"]},
{id:"covers",title:"Project Covers & Experiments",eyebrow:"Archive / Covers",story:"Standalone covers and visual experiments uploaded with the portfolio.",scope:"Cover design · Visual experiments · Project thumbnails",files:["khairzad.png","seredo.png","tab-beauty.png"]}
];

const $=s=>document.querySelector(s);
const fullSrc=f=>f.endsWith('.svg')?f:`web/full/${f}.webp`;
const selected=projects.filter(p=>p.featured);
const additional=projects.filter(p=>!p.featured);
let openId=null;

function projectMarkup(p,i,offset=0){return `<article class="project-item" data-id="${p.id}"><button class="project-trigger" type="button" aria-expanded="false"><span class="project-no">${String(i+1+offset).padStart(2,'0')}</span><span class="project-title">${p.title}</span><span class="project-meta">${p.eyebrow}<br>${p.files.length} ${p.files.length===1?'piece':'pieces'}</span><span class="project-arrow">+</span></button><div class="project-panel"><div class="project-panel-inner"><div class="project-content"><div class="project-copy"><p>${p.story}</p><div class="scope"><span class="scope-label">Scope</span><p class="scope-text">${p.scope}</p></div></div><div><div class="project-gallery" data-gallery></div><div class="gallery-count">${p.files.length} / ${p.files.length===1?'piece':'pieces'}</div></div></div></div></div></article>`}

function renderLists(){ $('#selectedProjects').innerHTML=selected.map((p,i)=>projectMarkup(p,i)).join(''); $('#additionalProjects').innerHTML=additional.map((p,i)=>projectMarkup(p,i,selected.length)).join(''); document.querySelectorAll('.project-trigger').forEach(btn=>btn.addEventListener('click',()=>toggleProject(btn.closest('.project-item')))); }

function buildGallery(item,p){const gallery=item.querySelector('[data-gallery]');if(gallery.dataset.ready)return;gallery.dataset.ready='1';gallery.innerHTML=p.files.map((f,i)=>`<figure class="work-figure" data-file="${f}" data-title="${p.title}"><img src="${fullSrc(f)}" data-original="${f}" alt="${p.title} — work ${i+1}" loading="lazy" decoding="async"></figure>`).join('');gallery.querySelectorAll('img').forEach(img=>{img.onerror=()=>{img.onerror=null;img.src=img.dataset.original}});gallery.querySelectorAll('.work-figure').forEach(fig=>fig.addEventListener('click',()=>openLightbox(fig.dataset.file,fig.dataset.title)))}

function toggleProject(item){const id=item.dataset.id;const p=projects.find(x=>x.id===id);if(openId===id){item.classList.remove('open');item.querySelector('.project-trigger').setAttribute('aria-expanded','false');openId=null;return}document.querySelectorAll('.project-item.open').forEach(el=>{el.classList.remove('open');el.querySelector('.project-trigger').setAttribute('aria-expanded','false')});buildGallery(item,p);item.classList.add('open');item.querySelector('.project-trigger').setAttribute('aria-expanded','true');openId=id;setTimeout(()=>item.scrollIntoView({behavior:'smooth',block:'nearest'}),120)}

const lightbox=$('#lightbox'),lightboxImage=$('#lightboxImage'),lightboxCaption=$('#lightboxCaption');
function openLightbox(file,title){lightboxImage.onerror=()=>{lightboxImage.onerror=null;lightboxImage.src=file};lightboxImage.src=fullSrc(file);lightboxCaption.textContent=title;lightbox.classList.add('open');lightbox.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeLightbox(){lightbox.classList.remove('open');lightbox.setAttribute('aria-hidden','true');lightboxImage.src='';document.body.style.overflow=''}
$('#lightboxClose').addEventListener('click',closeLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&lightbox.classList.contains('open'))closeLightbox()});

const root=document.documentElement,langToggle=$('#langToggle');let lang=localStorage.getItem('portfolioLang')||'en';
function applyLang(){const ar=lang==='ar';root.lang=lang;root.dir=ar?'rtl':'ltr';langToggle.textContent=ar?'EN':'AR';document.querySelectorAll('[data-en][data-ar]').forEach(el=>{const v=el.getAttribute(ar?'data-ar':'data-en');if(v.includes('<'))el.innerHTML=v;else el.textContent=v});localStorage.setItem('portfolioLang',lang)}
langToggle.addEventListener('click',()=>{lang=lang==='en'?'ar':'en';applyLang()});
renderLists();applyLang();